global using static GovcoreBse.Common.Constants;
global using ST = GovcoreBse.Common.Constants.Setting;
global using DK = GovcoreBse.Common.Constants.DataKey;
global using SK = GovcoreBse.Common.Constants.SessionKey;
global using static GovcoreBse.Common.Interfaces;
global using HelperT= GovcoreBse.Common.TypeHelper;
global using HelperS = GovcoreBse.Common.StringHelper;
global using HelperU = GovcoreBse.Common.UtilHelper;
global using HelperF = GovcoreBse.Common.FieldHelper;
global using static GovcoreBse.Common.FieldHelper;
global using static GovcoreBse.Common.StringHelper;
global using static GovcoreBse.Common.UtilHelper;
global using GovcoreBse.Common.Models;