global using CN = GovcoreBse.Common.Constants;
global using DK = GovcoreBse.Common.Constants.DataKey;
global using SK = GovcoreBse.Common.Constants.SessionKey;
global using IN = GovcoreBse.Common.Interfaces;
global using FN = GovcoreBse.Common.Adapt.Interfaces;
global using HelperS = GovcoreBse.Common.StringHelper;
global using HelperT = GovcoreBse.Common.TypeHelper;
global using GovcoreBse.Common.Models;
global using GovcoreBse.Shared.Tools;
global using GovcoreBse.Common;
