// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GovcoreBse.Store.Models;

public partial class BlazeLogDbContext : DbContext
{
    public BlazeLogDbContext(DbContextOptions<BlazeLogDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CoreRole> CoreRoles { get; set; }
    public virtual DbSet<CoreActivityLog> CoreActivityLogs { get; set; }

    public virtual DbSet<CoreFileDoc> CoreFileDocs { get; set; }

    public virtual DbSet<CoreSetting> CoreSettings { get; set; }

    public virtual DbSet<CoreUser> CoreUsers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CoreActivityLog>(entity =>
        {
            entity.Property(e => e.updatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CoreActivityLog_updatedAt");
        });

        modelBuilder.Entity<CoreFileDoc>(entity =>
        {
            entity.Property(e => e.updatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CoreFileDoc_updatedAt");
        });

        modelBuilder.Entity<CoreSetting>(entity =>
        {
            entity.Property(e => e.CanEdit).HasAnnotation("Relational:DefaultConstraintName", "DF_CoreSetting_CanEdit");
        });

        modelBuilder.Entity<CoreUser>(entity =>
        {
            entity.Property(e => e.Disabled).HasAnnotation("Relational:DefaultConstraintName", "DF_CoreUser_Disabled");
            entity.Property(e => e.level).HasAnnotation("Relational:DefaultConstraintName", "DF_CoreUser_level");
            entity.Property(e => e.updatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CoreUser_updatedAt");
        });

        modelBuilder.Entity<CoreRole>(entity =>
        {
            entity.Property(e => e.level)
                .HasDefaultValue(-1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CoreRole_level");
            entity.Property(e => e.updatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CoreRole_updatedAt");
        });


        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}