// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GovcoreBse.Store.Models;

[Table("CoreRole")]
public partial class CoreRole
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string LinkSystem { get; set; }

    public int level { get; set; }

    [StringLength(50)]
    public string RoleName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? updatedAt { get; set; }

    [StringLength(50)]
    public string updatedBy { get; set; }
}