// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GovcoreBse.Store.Models;

[Table("CoreActivityLog")]
public partial class CoreActivityLog
{
    [Key]
    public long Id { get; set; }

    public int UserKey { get; set; }

    [StringLength(100)]
    public string UserId { get; set; } = null!;

    [StringLength(50)]
    public string? ActivityType { get; set; }

    [StringLength(255)]
    public string? ActivityMessage { get; set; }

    public string? ActivityEncData { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? updatedAt { get; set; }

    [StringLength(50)]
    public string? updatedBy { get; set; }
}