// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GovcoreBse.Store.Models;

[Table("CoreFileDoc")]
public partial class CoreFileDoc
{
    [Key]
    public long Id { get; set; }

    [StringLength(50)]
    public string LinkTable { get; set; } = null!;

    public int LinkId { get; set; }

    [StringLength(50)]
    public string DocType { get; set; } = null!;

    public string UploadFilePath { get; set; } = null!;

    [StringLength(128)]
    public string RelativePath { get; set; } = null!;

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [Column("updatedBy")]
    [StringLength(50)]
    public string? UpdatedBy { get; set; }

    [Column("updatedPost")]
    [StringLength(50)]
    public string? UpdatedPost { get; set; }
}