// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GovcoreBse.Store.Models;

[Table("CoreSetting")]
public partial class CoreSetting
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string SettingId { get; set; } = null!;

    [StringLength(1000)]
    public string? SettingValue { get; set; }

    public bool CanEdit { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? updatedAt { get; set; }

    [StringLength(50)]
    public string? updatedBy { get; set; }
}